/*
-- SQL SCHEMA FOR SUPABASE DASHBOARD
-- Run these in the SQL Editor of your Supabase project

-- 1. Profiles table
create table profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  updated_at timestamp with time zone,
  avatar_url text
);

-- 2. Game Saves table
create table saves (
  user_id uuid references auth.users not null primary key,
  data jsonb not null,
  updated_at timestamp with time zone default now()
);

-- 3. Leaderboards table
create table leaderboards (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  username text,
  score bigint not null,
  wave int not null,
  created_at timestamp with time zone default now(),
  constraint unique_player_score unique (user_id)
);

-- Indices for performance
create index idx_leaderboard_score on leaderboards (score desc);
create index idx_leaderboard_user on leaderboards (user_id);

-- 4. Set up Row Level Security (RLS)
alter table profiles enable row level security;
alter table saves enable row level security;
alter table leaderboards enable row level security;

-- 5. Auto-create Profile Trigger (Expert Practice)
-- This function runs every time a new user signs up in Supabase Auth
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, split_part(new.email, '@', 1), new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Profiles: Users can read all, but only write their own
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can update their own profile." on profiles for update using (auth.uid() = id);

-- Saves: Users can only read/write their own data
create policy "Users can see their own saves." on saves for select using (auth.uid() = user_id);
create policy "Users can update their own saves." on saves for insert with check (auth.uid() = user_id);
create policy "Users can update their own saves." on saves for update using (auth.uid() = user_id);

-- Leaderboards: Everyone can read, users can only insert/update their own scores
create policy "Anyone can view leaderboard." on leaderboards for select using (true);
create policy "Users can submit their own scores." on leaderboards for insert with check (auth.uid() = user_id);
create policy "Users can update their own scores." on leaderboards for update using (auth.uid() = user_id);
*/
