// Bug Visual Definitions - Complete design system for 15 bug types
// Matches design spec from VISUAL_DESIGN_SYSTEM.md

export interface BugVisualDefinition {
  id: string;
  name: string;
  tier: 'alpha' | 'elite' | 'standard' | 'variant';
  shape: 'hex' | 'circle' | 'triangle' | 'diamond' | 'star';
  primaryColor: string;
  secondaryColor: string;
  glowColor: string;
  eyeColor: string;
  size: number;
  speed: number;
  colorMode: 'solid' | 'pulse' | 'cycle' | 'gradient';
  trailEnabled: boolean;
  trailColor?: string;
  deathVfx: 'explode' | 'dissolve' | 'shatter' | 'implode';
  specialEffect?: string;
}

// 15 unique bug visual definitions based on AAA design
export const BUG_VISUALS: Record<string, BugVisualDefinition> = {
  // Alpha Predators (Boss Tier)
  armored_beetle: {
    id: 'armored_beetle',
    name: 'Armored Beetle',
    tier: 'alpha',
    shape: 'hex',
    primaryColor: '#1a1a1a',
    secondaryColor: '#dc2626',
    glowColor: '#ff4444',
    eyeColor: '#ffff00',
    size: 55,
    speed: 35,
    colorMode: 'pulse',
    trailEnabled: false,
    deathVfx: 'shatter',
    specialEffect: 'armor_plates',
  },
  shadow_moth: {
    id: 'shadow_moth',
    name: 'Shadow Moth',
    tier: 'alpha',
    shape: 'star',
    primaryColor: '#1a0a2e',
    secondaryColor: '#aa44ff',
    glowColor: '#ff00ff',
    eyeColor: '#ffffff',
    size: 50,
    speed: 70,
    colorMode: 'cycle',
    trailEnabled: true,
    trailColor: '#9400d3',
    deathVfx: 'dissolve',
    specialEffect: 'phase_shift',
  },

  // Elite Bugs (Mini-Boss Tier)
  crystal_stag: {
    id: 'crystal_stag',
    name: 'Crystal Stag',
    tier: 'elite',
    shape: 'diamond',
    primaryColor: '#e0f2fe',
    secondaryColor: '#0ea5e9',
    glowColor: '#00ffff',
    eyeColor: '#f0f9ff',
    size: 48,
    speed: 55,
    colorMode: 'gradient',
    trailEnabled: true,
    trailColor: '#e0f2fe',
    deathVfx: 'shatter',
    specialEffect: 'prismatic',
  },
  venom_widow: {
    id: 'venom_widow',
    name: 'Venom Widow',
    tier: 'elite',
    shape: 'circle',
    primaryColor: '#14532d',
    secondaryColor: '#22c55e',
    glowColor: '#32cd32',
    eyeColor: '#fef08a',
    size: 46,
    speed: 42,
    colorMode: 'pulse',
    trailEnabled: true,
    trailColor: '#32cd32aa',
    deathVfx: 'dissolve',
    specialEffect: 'poison_aura',
  },
  thunder_hornet: {
    id: 'thunder_hornet',
    name: 'Thunder Hornet',
    tier: 'elite',
    shape: 'triangle',
    primaryColor: '#1c1917',
    secondaryColor: '#facc15',
    glowColor: '#ffff00',
    eyeColor: '#ff0000',
    size: 44,
    speed: 68,
    colorMode: 'flash',
    trailEnabled: true,
    trailColor: '#fbbf24',
    deathVfx: 'explode',
    specialEffect: 'lightning',
  },

  // Standard Bugs (Common Tier)
  ember_firefly: {
    id: 'ember_firefly',
    name: 'Ember Firefly',
    tier: 'standard',
    shape: 'circle',
    primaryColor: '#1c1917',
    secondaryColor: '#ea580c',
    glowColor: '#ff8800',
    eyeColor: '#fef08a',
    size: 28,
    speed: 52,
    colorMode: 'pulse',
    trailEnabled: true,
    trailColor: '#ff4500',
    deathVfx: 'explode',
    specialEffect: 'ember',
  },
  frost_needle: {
    id: 'frost_needle',
    name: 'Frost Needle',
    tier: 'standard',
    shape: 'diamond',
    primaryColor: '#164e63',
    secondaryColor: '#22d3ee',
    glowColor: '#00ffff',
    eyeColor: '#f0f9ff',
    size: 26,
    speed: 38,
    colorMode: 'pulse',
    trailEnabled: true,
    trailColor: 'rgba(34, 211, 238, 0.4)',
    deathVfx: 'dissolve',
    specialEffect: 'frost_trail',
  },
  magma_crawler: {
    id: 'magma_crawler',
    name: 'Magma Crawler',
    tier: 'standard',
    shape: 'circle',
    primaryColor: '#111827',
    secondaryColor: '#dc2626',
    glowColor: '#ff4400',
    eyeColor: '#ffaaaa',
    size: 32,
    speed: 28,
    colorMode: 'pulse',
    trailEnabled: true,
    trailColor: '#ff4400aa',
    deathVfx: 'explode',
    specialEffect: 'lava_pool',
  },
  electric_jolt: {
    id: 'electric_jolt',
    name: 'Electric Jolt',
    tier: 'standard',
    shape: 'star',
    primaryColor: '#1e3a5f',
    secondaryColor: '#facc15',
    glowColor: '#ffff00',
    eyeColor: '#00ffff',
    size: 24,
    speed: 72,
    colorMode: 'flash',
    trailEnabled: true,
    trailColor: '#fbbf24',
    deathVfx: 'explode',
    specialEffect: 'arc',
  },
  shadow_leech: {
    id: 'shadow_leech',
    name: 'Shadow Leech',
    tier: 'standard',
    shape: 'circle',
    primaryColor: '#000000',
    secondaryColor: '#991b1b',
    glowColor: '#ff0000',
    eyeColor: '#fecaca',
    size: 30,
    speed: 32,
    colorMode: 'fade',
    trailEnabled: true,
    trailColor: '#000000aa',
    deathVfx: 'implode',
    specialEffect: 'burrow',
  },

  // Existing bugs still need visual upgrades
  basic: {
    id: 'basic',
    name: 'Basic Bug',
    tier: 'standard',
    shape: 'circle',
    primaryColor: '#3b82f6',
    secondaryColor: '#60a5fa',
    glowColor: '#3b82f6',
    eyeColor: '#ffffff',
    size: 24,
    speed: 40,
    colorMode: 'solid',
    trailEnabled: false,
    deathVfx: 'explode',
  },
  scout: {
    id: 'scout',
    name: 'Scout Bug',
    tier: 'standard',
    shape: 'circle',
    primaryColor: '#22c55e',
    secondaryColor: '#86efac',
    glowColor: '#22c55e',
    eyeColor: '#ffffff',
    size: 20,
    speed: 72,
    colorMode: 'solid',
    trailEnabled: true,
    trailColor: 'rgba(34, 197, 94, 0.4)',
    deathVfx: 'explode',
  },
  tank: {
    id: 'tank',
    name: 'Tank Bug',
    tier: 'standard',
    shape: 'hex',
    primaryColor: '#78716c',
    secondaryColor: '#d6d3d1',
    glowColor: '#9ca3af',
    eyeColor: '#ef4444',
    size: 38,
    speed: 22,
    colorMode: 'solid',
    trailEnabled: false,
    deathVfx: 'shatter',
  },
  phase: {
    id: 'phase',
    name: 'Phase Bug',
    tier: 'standard',
    shape: 'diamond',
    primaryColor: '#7c3aed',
    secondaryColor: '#a78bfa',
    glowColor: '#8b5cf6',
    eyeColor: '#ffffff',
    size: 30,
    speed: 45,
    colorMode: 'pulse',
    trailEnabled: true,
    trailColor: 'rgba(139, 92, 246, 0.4)',
    deathVfx: 'dissolve',
  },
  ember: {
    id: 'ember',
    name: 'Ember Bug',
    tier: 'standard',
    shape: 'circle',
    primaryColor: '#b91c1c',
    secondaryColor: '#f97316',
    glowColor: '#ff4400',
    eyeColor: '#fef08a',
    size: 28,
    speed: 38,
    colorMode: 'pulse',
    trailEnabled: true,
    trailColor: '#ff4500',
    deathVfx: 'explode',
  },
  frost: {
    id: 'frost',
    name: 'Frost Bug',
    tier: 'standard',
    shape: 'diamond',
    primaryColor: '#0e7490',
    secondaryColor: '#22d3ee',
    glowColor: '#00ffff',
    eyeColor: '#f0f9ff',
    size: 26,
    speed: 35,
    colorMode: 'pulse',
    trailEnabled: true,
    trailColor: 'rgba(34, 211, 238, 0.4)',
    deathVfx: 'dissolve',
  },
};

// Helper to get visual definition for bug type
export function getBugVisual(type: string): BugVisualDefinition {
  return BUG_VISUALS[type] || BUG_VISUALS.basic;
}
